# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a078ebc8bb9f350650d30036f3618fe0089bb6f0daa1475eaaa6c2fbd811bafe0e85b556383171acefaf342f6fb7486193ba98c797f6d2e35018d890d27096c8

test:
  secret_key_base: 744962d1f3581c481d3dbf5ee300606e2d869cccec626c89e3a8f2fa9211404c3058131c014f8d039c864d357efd2c017645f49994abad685ea059136cfd4540

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
